name: Continuous Integration

on:
  push:
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-18.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    - run: docker-compose build test
    - name: Run tests
      run: make test
